#服务启动端口
server :  
  port :  8080

#数据库配置
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://106.54.165.228:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  #Mybatis mapper 映射路径配置
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.auto.entity

#redis配置
redis:
  # 连接的那个数据库
  database: 0
  # redis服务的ip地址
  host: 127.0.0.1
  # redis端口号
  port: 6379
  # redis连接超时时间（单位毫秒）
  timeout: 0